### ISSUE TITLE
Implement "Plan connector"

### ISSUE THREAD

**Issue by zambrovski** [holunda-io/camunda-8-connector-gpt#39]
To support more complex use cases it is useful first to create a plan and then execute the step.
This connector is responsible for creating a plan. A trivial plan consists of exactly one step, so the connector could run in mode choose the next action.

The main idea behind this connector is the following approach. The "plan connector" creates a plan consisting of multiple steps. Every step is a possible call to other connector, so the input of the step connector is part of the output of the plan connector. To constraint the plan creation, there must be a way telling the plan connector, which steps are possible. To do so, it needs a configuration describing every possible connector as a tuple of:

- connector name (customer connector)
- purpose (Look up customer information)

Imaging the plan connector has the ability to:

- customer connector / Look up customer information
- compose connector / Compose texts including requests if some information is required or answers to customer requests
- email connector / Send emails to customers if email address is available

For a plan connector, having the following task description: 

"Retrieve assessment of our customer care performance for the customer"

The possible plan could look like this:

1. name: customer connector, expected action: Retrieve customer email address, name and language
2. name: compose connector, expected action: Write an email to the customer, requesting the satisfaction of the customer about the sales department
3. name: send email to the customer

Having this plan, we could put a multi instance (or a loop using control flow in BPMN), having a call activity calling the connector dynamically based on the connector name....

Just as an idea...

Details are missing, but let start thinking on implementation

The possible inputs for this

**Comment by Benjoyo** [comment]
Few additional thoughts:

Compared to the currently popular agent execution scheme of thinking action to action, up-front planning has the advantage of reducing the risk of the agent loosing focus. On the downside, however, a fixed plan may limit the agent's ability to recover from errors and unforeseen observations. That's why I think (maybe not in the first implementation) the planner needs the possibility to re-evaluate and alter the plan during execution. 
I suggest a BPMN loop that re-activates the planner after every action/tool execution:

1. Initially, the planner outputs a plan consisting of a list of `steps` (see above comment). It also initializes a variable `results` as empty list. (and maybe a counter `currentStep`, although it is clear from the other two lists)
2. A gateway can call the action/tool for the current step
3. Result is appended to `results` list
4. Planner is activated again, re-evaluating the plan based on the latest result. May add/remove/modify upcoming steps.
5. Continue at 2. until planner executed with a complete result list and did not add any new step (therefore decided the overall task is complete)

Probably, in the last step, the planner also has the job of consolidating the results into a final result with respect to the overall task. The last result from an action/tool is not necessarily what was asked by the user.

**Comment by Benjoyo** [comment]
Now starting to work on this. Will start with a simpler version, without dynamic plan refinement.

Also, I will (at least for starters) split this into two connectors:
- planner
- executor

Why?
- separation of concerns
- possibility to review/alter plan with user task before execution
- there is a difference between a step in a high level plan and the actual input to the current connector. At each step, we need to derive a concrete task for a connector based on the current step and intermediate results from previous steps
